# Generated by Django 4.0.4 on 2022-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('type', models.CharField(max_length=60)),
                ('captured', models.BooleanField(default=False)),
                ('image', models.URLField()),
            ],
        ),
    ]
